# Dockerfile.dev
FROM node:20-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

# Change --frozen-lockfile to --no-frozen-lockfile
RUN corepack enable && pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 3000
CMD ["pnpm", "dev"]